### ISSUE TITLE
Fix: 모임 만들기 수정

### ISSUE THREAD

**Issue by BeMatthewsong** [INtiful/SootheWithMe#101]
## 📝 설명

- [x] 시간 관련한 속성 합치기 (selectedTime, dateTime)
- [x] ~~캐시 관련~~
- [x] form 태그
- [x] formdata
- [x] 이미지형식 확인 (mock image 전송 이슈)
- [x] 이미지 크기 제한 (1MB)

**Comment by HMRyu** [comment]
민혁님! 저 지금 develop 에서 받아서 모임 만들고 받아봤는데, 보내지고 받는건 문제 없는 것 같습니다!

다만, 이미지 보낼 때만 이슈가 생기는 것 같아요..!

이미지 전송을 했는데 mock image 로 표시됩니다!

이미지 관련 부분 확인해주시면 좋을 것 같습니다 : )

**Comment by BeMatthewsong** [comment]
<img width="786" alt="image" src="https://github.com/user-attachments/assets/6abd2e94-56f4-429b-9a80-fd896e8d3049">
