### ISSUE TITLE
Fix: 에러 모음집

### ISSUE THREAD

**Issue by BeMatthewsong** [INtiful/SootheWithMe#112]
## 📝 설명
에러를 발견하시면 여기 이슈에 댓글을 달아주세요.

에러를 발견한 상황과 에러를 캡쳐해주세요!

**Comment by BeMatthewsong** [comment]
## 로그인 이후 User 데이터 바로 못 가져오는 이슈 (✅ 해결 완료)

1) 로그인 관련 토큰이 있을 때만 모임 만들기가 가능해야 하는데, 로그인을 하고 나서 한동안 유저 데이터가 없습니다.
2) 또한, 로그아웃을 해도 유저 데이터가 남아있습니다.

새로고침을 해야 유저 데이터를 불러옵니다.

### 로그인한 직후
isUserNull -> true
userData -> null
![image](https://github.com/user-attachments/assets/c9bab4f7-2ab5-432f-8567-931335545880)

### 새로고침 이후
 isUserNull -> false
userData -> {...}
![image](https://github.com/user-attachments/assets/208f9a9f-a275-4761-a452-d9360bcc39be)

**Comment by BeMatthewsong** [comment]
> ## 로그인 이후 User 데이터 바로 못 가져오는 이슈

로그인하거나 로그아웃을 했을 때 새로고침하는 로직을 넣는 건 어떨까요?

**Comment by hakyoung12** [comment]
> ## 로그인 이후 User 데이터 바로 못 가져오는 이슈
혹시 컨텍스트로 유저를 받아오고 있나요? 
page컴포넌트에서 getUserData()를 통해서 서버사이드로 userData를 받아오면 해결될 것 같아보입니다.
src/app/layout.tsx 파일을 보시면 참고되실거에요...!

**Comment by hakyoung12** [comment]
## 모임 만들기 모달 모바일 사이즈에서 스크롤 안되는 이슈 (✅ 해결 완료)

1. 현재 모바일 사이즈에서 모임 만들기 모달에서 스크롤이 안되고 있습니다.

<img width="518" alt="스크린샷 2024-10-01 오후 1 41 50" src="https://github.com/user-attachments/assets/18505e34-02dc-44e1-acb9-75fd28a069b0">

**Comment by BeMatthewsong** [comment]
> ## 모임 만들기 모달 모바일 사이즈에서 스크롤 안되는 이슈
> 1. 현재 모바일 사이즈에서 모임 만들기 모달에서 스크롤이 안되고 있습니다.
> 
> <img alt="스크린샷 2024-10-01 오후 1 41 50" width="518" src="https://private-user-images.githubusercontent.com/159985297/372322204-18505e34-02dc-44e1-acb9-75fd28a069b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTgyNjAsIm5iZiI6MTcyNzc1Nzk2MCwicGF0aCI6Ii8xNTk5ODUyOTcvMzcyMzIyMjA0LTE4NTA1ZTM0LTAyZGMtNDRlMS1hY2I5LTc1ZmQyOGEwNjliMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwNDQ2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzI3NGQzOGUyMzM3ODU1ODQzYWY0MTU3MzkxMGMxNzdhNDZhNDA4ODlkNDk2NDg5NDhhMDc5MmM1ZDNlMjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vXkhBD-USsSuzveJ1rmWsqUYpFqM2bweoJZ6HtT4TtE">

![image](https://github.com/user-attachments/assets/d28d4ea0-7909-4b82-8b4e-a410e9d0cfda)
max-h-[100lvh] <- 이 값을 추가하시면 돼요! (MakeGatheringModal 컴포넌트입니다)

**Comment by BeMatthewsong** [comment]
> > ## 로그인 이후 User 데이터 바로 못 가져오는 이슈
> 
> 혹시 컨텍스트로 유저를 받아오고 있나요? page컴포넌트에서 getUserData()를 통해서 서버사이드로 userData를 받아오면 해결될 것 같아보입니다. src/app/layout.tsx 파일을 보시면 참고되실거에요...!

![image](https://github.com/user-attachments/assets/10144f6f-4a79-4e5f-a975-217b057d5a39)
감사합니다 정상적으로 작동합니다! layout에서 userData 받아서 props로 내려주는 방식을 이용해서 유저 데이터 전달했습니다!

**Comment by BeMatthewsong** [comment]
## 모임 보내주기 버튼 눌렀을 때 동작  (✅ 해결 완료)
![image](https://github.com/user-attachments/assets/c25913e1-7231-4449-8b7d-1c72e9356b6c)

Bye 버튼 누르면 찜하기 목록으로 이동되는 이슈

**Comment by BeMatthewsong** [comment]
## 토큰 유효 기간이 끝나도 남아있는 GNB 프로필 상태 (✅ 해결 완료)
![image](https://github.com/user-attachments/assets/9a1e3edf-c1d7-45dc-b15f-0152931a7e3e)

**Comment by BeMatthewsong** [comment]
## 시간 칩 이슈 (✅ 해결 완료)
형식이 달라져야 할 것 같습니다!
9:0 -> 09:00
![image](https://github.com/user-attachments/assets/bbc7a67a-460d-46bd-99e3-0ffb96c7f222)

**Comment by HMRyu** [comment]
> ## 시간 칩 이슈
> 형식이 달라져야 할 것 같습니다! 9:0 -> 09:00 ![image](https://private-user-images.githubusercontent.com/98685266/372724418-bbc7a67a-460d-46bd-99e3-0ffb96c7f222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDI4MzYsIm5iZiI6MTcyNzg0MjUzNiwicGF0aCI6Ii85ODY4NTI2Ni8zNzI3MjQ0MTgtYmJjN2E2N2EtNDYwZC00NmJkLTk5ZTMtMGZmYjk2YzdmMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA0MTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZjM3MmFjNDgyNmQ2MmE1YjFjNTY2YjE3MjdlYzczMDE0ZDA4ZGM1N2MwMjM2YmVhMGU5MTQ1YmZmOWI5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZowT8619kF1Xe8aObYJJQG8XeoWc1z8QA2y-oPZ2yVU)

~~확인해보겠습니다!~~

### 해결 완료했습니다!

<img width="149" alt="스크린샷 2024-10-02 14 21 54" src="https://github.com/user-attachments/assets/8e7649e5-ea39-4c97-a480-3f775dbbbe19">

**Comment by BeMatthewsong** [comment]
## 모임 모집 기간이 끝나고 모임을 취소하고 싶을 때, 취소(삭제)가 안 됩니다.
![image](https://github.com/user-attachments/assets/f8e65b8d-9323-4a83-811b-4ffcce67edf1)

**Comment by yunchaeney** [comment]
> ## 모임 보내주기 버튼 눌렀을 때 동작  (✅ 해결 완료)
> 
> Bye 버튼 누르면 찜하기 목록으로 이동되는 이슈

~~해당 부분 수정하여 다음 PR에 함께 올리겠습니다.~~
 ✅ 해결 완료

**Comment by yunchaeney** [comment]
## 모바일 화면에서 상단 GNB (✅ 해결 완료)
![image](https://github.com/user-attachments/assets/b6ad294e-eb2b-4d3d-b689-c25ca6ed743f)

모바일 환경에서 토큰 유효시간 부분이 왼쪽 메뉴와 붙어버려 UI가 이상한 것 같습니다.
모바일 환경에서는 유효시간을 안 보이게 하거나 / 프로필 클릭 시 드롭다운에 같이 넣거나 등
처리가 필요할 것 같습니다

**Comment by HMRyu** [comment]
# 모임 생성 후 모임 목록에 바로 반영이 안 되는 이슈

https://github.com/user-attachments/assets/03a9e93f-483c-4644-99bd-8009abc821a9

- 모임 생성 후 모임 목록에 모임이 바로 반영이 되지 않고 새로고침을 해야 반영됩니다!

**Comment by BeMatthewsong** [comment]
## 리뷰가 이상한 데 있음 (✅ 해결 완료)
![image](https://github.com/user-attachments/assets/269c9f6c-88ee-478a-ba74-1ff439156626)

**Comment by hakyoung12** [comment]
> ## 모바일 화면에서 상단 GNB (✅ 해결 완료)

<img width="328" alt="스크린샷 2024-10-07 오후 2 10 07" src="https://github.com/user-attachments/assets/8c9dffc3-ce28-48d7-b925-7aed0be0499b"></br>
모바일에서는 드롭다운메뉴에서 남은 시간을 볼 수 있도록 수정했습니다!
