### ISSUE TITLE
Fix: 모임 만들기 이후 바로 반영하기 

### ISSUE THREAD

**Issue by BeMatthewsong** [INtiful/SootheWithMe#129]
## 📝 설명

- [x] 3가지 중에 한 가지 방법 사용
- RQ mutate
- router.push
- router.refresh

- [x] name 프로퍼티 반영

**Comment by BeMatthewsong** [comment]
/gatherings/[id]

**Comment by HMRyu** [comment]
router.push 하여 모임 생성 시 바로 이동하도록 수정했습니다!

PR 확인 후 이슈 닫아주셔도 좋을 것 같아요!
