### ISSUE TITLE
Refactor: Chips, Filters 공통 컴포넌트 통합 

### ISSUE THREAD

**Issue by yunchaeney** [INtiful/SootheWithMe#147]
## 📝 설명
- 모임찾기 / 찜한모임 / 모든리뷰 에서 공통으로 사용되는 Chips, Filters 컴포넌트가 각각 페이지 상 약간의 차이점으로 별개 파일로 존재함.
- 이를 하나의 공통 컴포넌트로 만들고 확장성이 있도록 리팩토링하여, 하나의 컴포넌트를 모든 페이지에서 활용할 수 있게 리팩토링

- [x] Chips
- [x] Filters

**Comment by yunchaeney** [comment]
@HMRyu 
Chips 컴포넌트들을 확인한 결과, 가장 큰 차이점이 activeChips 상태를 컴포넌트에서 관리하는가 로 보여집니다.
useGathering 훅 내부에서도 selectedChips 상태를 useState로 관리하고, Chips 컴포넌트 내부에서도 activeChips로 화면상 선택된 칩을 보여지는 상태를 관리하고 있는 것 같습니다.
(api 호출 시 type을 결정하는 훅 내부의 상태와, UI 상 선택된 칩을 보여주는 컴포넌트 내부의 상태가 별도로 존재)

두 개 상태를 별도로 관리하는 이유가 무엇인지 여쭤보고 싶습니다!

**Comment by yunchaeney** [comment]
상태가 별도로 관리되고 있음에 있어서 문제는, 탭이나 chip 변경 시 UI가 동기화 되지 않는다는 점 같습니다.

현재 달램핏에서 [마인드풀니스] 를 선택하고 워케이션으로 넘어가면, `selectedChip` (훅 내부에서 관리되는 상태) 는 null 상태가 됩니다.
이때 다시 달램핏으로 돌아오면, `selectedChip` 은 null 상태라 달램핏 type으로 데이터를 조회하는데,
Chips 컴포넌트 내부의 `activeChip` 상태는 여전히 [마인드풀니스] 상태로 유지되어 chip은 마인드풀니스가 활성화된 상태입니다.

이와 같은 문제점 등이 있어, 별도로 상태 관리하는 특별한 이유가 있으신지,
만약 없으시다면 reviews 페이지의 Chips처럼 selected를 props로 내려주는 방식으로 개선해도 괜찮을지 여쭤보고 싶습니다!

**Comment by HMRyu** [comment]
> @HMRyu Chips 컴포넌트들을 확인한 결과, 가장 큰 차이점이 activeChips 상태를 컴포넌트에서 관리하는가 로 보여집니다. useGathering 훅 내부에서도 selectedChips 상태를 useState로 관리하고, Chips 컴포넌트 내부에서도 activeChips로 화면상 선택된 칩을 보여지는 상태를 관리하고 있는 것 같습니다. (api 호출 시 type을 결정하는 훅 내부의 상태와, UI 상 선택된 칩을 보여주는 컴포넌트 내부의 상태가 별도로 존재)
> 
> 두 개 상태를 별도로 관리하는 이유가 무엇인지 여쭤보고 싶습니다!

우선, UI 때문에 별도로 관리했습니다!

달램핏, 워케이션 탭을 누르는 UI, 그리고 달램핏 내부의 Chip UI 가 존재하기 때문에 별도로 관리했습니다.

다음으로는, API 때문에 별도로 관리했습니다!

api 전송 시 `type` 을 필수로 넣어주어야 하는데,

api 가 받는 `type` 이 총 네 가지입니다. 달램핏, 워케이션, 오피스 스트레칭, 마인드풀니스.

그런데, 달램핏 내부에 오피스 스트레칭, 마인드풀니스가 존재하기 때문에
`type` 으로 달램핏만 보내는 경우, 오피스 스트레칭 또는 마인드풀니스를 보내는 경우를 나눠서 생각하려고 상태를 따로 관리했습니다..!

이러한 이유들로 상태를 나눠서 관리중인데, type 전송 시 데이터가 중복되는 이슈가 없다면 props 로 내려주는 방식도 좋을 것 같습니다!

**Comment by yunchaeney** [comment]
일단 해당 부분도 props로 내려주는 방식으로 바꾸어, Chips 컴포넌트를 하나로 통합, 리팩토링 해보겠습니다~!
**type 전송 시 데이터가 중복되는 이슈** 꼼꼼하게 확인해서 리팩토링 하고 혹시 문제 생기면 말씀 드리겠습니다. 감사합니다!
