### ISSUE TITLE
Style: 다크모드 추가

### ISSUE THREAD

**Issue by HMRyu** [INtiful/SootheWithMe#148]
## 📝 설명
- 다크모드 기능 추가

**Comment by yunchaeney** [comment]
다크모드 적용 시 컬러 디자인을 임시로 적용해 보았습니다!
기존 `var-gray` 색상은 푸른끼가 많아, 메인 컬러인 주황색과 너무 어울리지 않는 것 같아서
tailwind의 `Neutral` 컬러맵을 사용했습니다.

![image](https://github.com/user-attachments/assets/2171f02c-4920-4886-bd11-5212c5d199f3)

피드백 주시면 감사하겠습니다..!

@HMRyu @hakyoung12 @BeMatthewsong

**Comment by BeMatthewsong** [comment]
저는 채현님 디자인이 더 자연스러운 것 같아서 좋습니다!

**Comment by hakyoung12** [comment]
저도 채현님 디자인이 좋다고 생각합니다!

**Comment by HMRyu** [comment]
저도 채현님 디자인이 더 보기에 좋은 것 같아요!

이걸로 반영해도 좋을 것 같습니다..!
