### ISSUE TITLE
Fix: /mypage 접속 시 에러 발생 (미들웨어랑 msw 충돌)

### ISSUE THREAD

**Issue by HMRyu** [INtiful/SootheWithMe#193]
### /mypage

<img width="962" alt="스크린샷 2024-10-16 13 02 51" src="https://github.com/user-attachments/assets/eb7de3a8-5062-4cf9-a55d-37bf2ba4e40c">

mypage 접속 시 위와 같은 에러 발생.
msw, playwright 세팅하면서 webpack 과 관련된 문제인 것 같아서 확인 중

**Comment by BeMatthewsong** [comment]
최후의 보루...
- msw 관련된 PR revert
참고 > https://jjang-j.tistory.com/77

**Comment by BeMatthewsong** [comment]
![image](https://github.com/user-attachments/assets/7eaff45d-3a34-4b00-b0fe-79bcaa000983)

CD 과정에서 확인할 수 있습니다

**Comment by BeMatthewsong** [comment]
미들웨어랑 MSW 랑 서로 api 요청을 뺏으려고 해서 충돌이 일어났다

**Comment by BeMatthewsong** [comment]
![image](https://github.com/user-attachments/assets/8e9797f3-bd48-4145-89f2-94b89499614f)

**Comment by BeMatthewsong** [comment]
## 해결 완료 ✅

![image](https://github.com/user-attachments/assets/746a2d7e-d60e-4d66-be19-6999bad2c590)
미들웨어랑 MSW 랑 서로 api 요청을 뺏으려고 해서 충돌이 일어났었고, 토큰이 없으면 로그인 페이지로 넘어가도록 만든 미들웨어는 우선 제거하기로 했습니다.
> 해결 PR  #195
