### ISSUE TITLE
Setting: SEO 세팅

### ISSUE THREAD

**Issue by yunchaeney** [INtiful/SootheWithMe#216]
## 📝 설명
검색 엔진 최적화(search engine optimization) 를 위한 작업에 대한 설명입니다.

## 1. 각 페이지별 메타데이터 생성
웹사이트의 메타데이터는 검색 엔진과 소셜 미디어 플랫폼에서 페이지의 내용을 설명하는 요소입니다. 메타데이터를 최적화하면 사용자와 검색 엔진 모두에게 유용한 정보를 제공할 수 있습니다.

### 타이틀 태그와 메타 설명
루트 layout 및 각 페이지 별로 타이틀 태그와 메타 설명을 작성했습니다. 
```
title: {
    template: '%s | Soothe With Me',
    default: 'Soothe With Me',
  },
```

위와 같이 title의 template를 지정하여, 페이지 이름 및 사이트명이 함께 노출되도록 하였습니다. _( ex : '모임 찾기 |  Soothe With Me')_

### Open Graph 및 Twitter 카드 
소셜 미디어에서의 공유를 최적화하기 위해 Open Graph 메타 태그와 Twitter 카드 정보를 추가했습니다.
특히 모임 상세 페이지는, 모임의 이름, 종류, 이미지를 포함하여 공유되도록 설정하였습니다.
![image](https://github.com/user-attachments/assets/2582e106-816d-4f25-8e25-ef35cad285f0)

## 2. Sitemap.xml 파일과 robots.txt 파일 생성
`next-sitemap`  패키지를 이용하면 좀 더 편리하게 설정이 가능하나, 서치 결과 어떤 환경에서는 제대로 동작하지 않는 등 이슈가 있다고 하여 직접 설정하는 방식으로 진행하였습니다.

### Sitemap.xml
검색 엔진이 사이트의 페이지 구조를 이해하는 데 도움을 줍니다. **페이지 URL, 마지막 수정일, 우선순위** 등을 포함하여 검색 엔진이 사이트를 효율적으로 크롤링할 수 있도록 도와줍니다.
기본적으로 `xml` 파일 형식이어야 하지만, Next.js는 `js|ts` 파일 형식으로 사이트맵을 동적으로 생성할 수 있어 좀 더 편리하게 적용할 수 있습니다.  [공식문서](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap) 참고

### robots.txt
검색 엔진 크롤러가 어떤 페이지를 크롤링하고 어떤 페이지를 크롤링하지 말아야 하는지를 지정합니다. 
`Disallow: /mypage/ ` 코드를 넣어, 로그인 후 접근 가능한 마이페이지는 크롤링 되지 않도록 설정하였습니다.

## 3. Google Search Console 설정
Google Search Console은 웹사이트의 성능을 모니터링하고, 검색 트래픽 및 인덱싱 상태를 분석하는 도구입니다.
Google Search Console에 사이트 도메인을 추가 후 소유권 인증을 통해 등록할 수 있습니다.
소유권 확인 방법은 아래와 같습니다.
![image](https://github.com/user-attachments/assets/3426bf88-f7f0-401b-960e-6bc2259b36a7)

HTML 메타 태그를 삽입하는 방식으로 진행했으며, 메타데이터는 아래와 같은 방식으로 설정할 수 있습니다.
```
export const rootMetadata = {
  //..... 생략
  other: {
    'google-site-verification': 제공 받은 넘버,
  },
};
```

이후 콘솔에서 검색 성능을 모니터링 할 수 있습니다. (현재는 데이터 수집 중으로 결과가 나오지 않습니다.)
![image](https://github.com/user-attachments/assets/fd59d750-40ab-4136-818c-cefde5696186)

이는 어떤 키워드로 방문자가 유입되고 있는지, 클릭 수와 노출 수는 어떤지 등을 분석할 수 있어 지속적으로 모니터링 하며 제품을 개선해 나가는 데 도움을 줍니다.

**Comment by BeMatthewsong** [comment]
퀄리티 미쳤네요

**Comment by HMRyu** [comment]
SEO 세팅을 해 본 적이 없었는데, 저희 프로젝트에 적용하니까 너무 좋네요..!

더 공부해보겠습니다 :)
