### ISSUE TITLE
Fix: 개설확장된 모임인데 어둡게 처리되는 이슈

### ISSUE THREAD

**Issue by BeMatthewsong** [INtiful/SootheWithMe#225]
## 📝 설명
<img width="937" alt="image" src="https://github.com/user-attachments/assets/7fd9b271-0e98-423b-ab70-c4a95ad06827">

제가 생각했을 때 어둡게 처리하면 뭔가 마감된 모임이랑 개설 확정된 모임이 구분이 안 간다고 판단이 듭니다.
어둡게 처리된 걸 없애는 건 어떠신지요?

**Comment by HMRyu** [comment]
넵 확인했습니다!
반영해서 PR 올리도록 하겠습니다~!
